"""remove_zipcode_in_education

Revision ID: a4f1641f2ce2
Revises: d0d497effb95
Create Date: 2023-05-02 16:08:29.475193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f1641f2ce2'
down_revision = 'd0d497effb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###