"""create education

Revision ID: d0d497effb95
Revises: 384e4aa60b94
Create Date: 2023-04-26 09:49:05.167188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d497effb95'
down_revision = '384e4aa60b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=75), nullable=True),
    sa.Column('school', sa.String(length=75), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=75), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educations')
    # ### end Alembic commands ###