"""add_degree_from_education

Revision ID: ca63a78dcd0d
Revises: d0d497effb95
Create Date: 2023-05-02 17:01:29.248352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca63a78dcd0d'
down_revision = 'd0d497effb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree', sa.String(length=75), nullable=True))
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.INTEGER(), nullable=False))
        batch_op.drop_column('degree')

    # ### end Alembic commands ###